# Generated by Django 5.2.10 on 2026-01-18 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название лицензии')),
                ('img', models.ImageField(upload_to='images/license/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Лицензия',
                'verbose_name_plural': 'Лицензии',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Направление')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Шифр')),
                ('edu_level', models.CharField(choices=[('bachelor', 'Бакалавриат'), ('master', 'Магистратура'), ('specialist', 'Специалитет')], max_length=20, verbose_name='Уровень образования')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название приказа')),
                ('file', models.FileField(upload_to='orders/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Приказ',
                'verbose_name_plural': 'Приказы',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Профиль')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True, verbose_name='Slug')),
                ('study_form', models.CharField(choices=[('full_time', 'Очная'), ('part_time', 'Заочная')], max_length=20, verbose_name='Форма обучения')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.major', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ['major', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название дисциплины')),
                ('annotation', models.FileField(blank=True, null=True, upload_to='modules/annotation/', verbose_name='Аннотация')),
                ('syllabus', models.FileField(blank=True, null=True, upload_to='modules/syllabus/', verbose_name='Рабочая программа')),
                ('assesment_fund', models.FileField(blank=True, null=True, upload_to='modules/assesment/', verbose_name='Фонд оценочных средств')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Дисциплина / Модуль / Практика',
                'verbose_name_plural': 'Дисциплины / Модули / Практики',
            },
        ),
        migrations.CreateModel(
            name='CompetencePassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('file', models.FileField(blank=True, null=True, upload_to='passports/', verbose_name='Файл')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competence_passports', to='core.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Паспорт / Программа компетенций',
                'verbose_name_plural': 'Паспорта / Программы компетенций',
            },
        ),
        migrations.CreateModel(
            name='ProfileDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('file', models.FileField(blank=True, null=True, upload_to='profiles/', verbose_name='Файл')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Документ профиля',
                'verbose_name_plural': 'Документы профиля',
            },
        ),
    ]
