# Generated by Django 5.2.10 on 2026-01-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='text',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
    ]
