# Generated by Django 5.2.10 on 2026-01-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_license_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('kr_laws', 'Кыргыз Республикасынын мыйзамдары'), ('gov_resolution', 'Кыргыз Республикасынын Өкмөтүнүн жоболору'), ('ministry_orders', 'Кыргыз Республикасынын Илим, жогорку билим берүү министрлигинин буйруктары'), ('nsu_orders', 'Нарын мамлекеттик университетинин буйруктары')], default='nsu_orders', max_length=50, verbose_name='Категория'),
        ),
    ]
