# Generated by Django 5.2.10 on 2026-01-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Закон/Приказ', 'verbose_name_plural': 'Законы / Приказы / Постановлении'},
        ),
        migrations.RemoveField(
            model_name='license',
            name='img',
        ),
        migrations.AddField(
            model_name='license',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='images/license/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='major',
            name='edu_level',
            field=models.CharField(choices=[('bachelor', 'Бакалавриат'), ('master', 'Магистратура'), ('specialist', 'Специалитет'), ('srednee', 'Орто кесиптик')], max_length=20, verbose_name='Уровень образования'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='study_form',
            field=models.CharField(choices=[('full_time', 'Күндүзгү'), ('part_time', 'Сырттан')], max_length=20, verbose_name='Форма обучения'),
        ),
    ]
