# Generated by Django 5.2.10 on 2026-02-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_options_remove_license_img_license_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('kr_laws', 'Кыргыз Республикасынын мыйзамдары'), ('gov_resolution', 'Кыргыз Республикасынын Өкмөтүнүн жоболору'), ('ministry_orders', 'Кыргыз Республикасынын Илим, жогорку билим берүү министрлигинин буйруктары'), ('nsu_orders', 'Нарын мамлекеттик университетинин буйруктары'), ('smk1', 'CMK 1'), ('smk2', 'CMK 2')], default='nsu_orders', max_length=50, verbose_name='Категория'),
        ),
    ]
