# Generated by Django 5.2.10 on 2026-02-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_order_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to='schedules/', verbose_name='Файл (PDF)')),
                ('faculty', models.CharField(choices=[('atf', 'Агрардык-техникалык факультети'), ('ped', 'Педагогика факультети'), ('phil', 'Филология факультети'), ('econom', 'Экономика жана табигый-гуманитардык илимдер факультети'), ('it', 'Чет тилдери жана компьютердик системаларды программалоо')], default='atf', max_length=100, verbose_name='Факультет/колледж')),
            ],
            options={
                'verbose_name': 'Учебное расписание',
                'verbose_name_plural': 'Учебные расписания',
                'ordering': ['faculty', 'title'],
            },
        ),
    ]
