# Generated by Django 5.2.10 on 2026-02-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('kr_laws', 'Кыргыз Республикасынын мыйзамдары'), ('gov_resolution', 'Кыргыз Республикасынын Өкмөтүнүн жоболору'), ('ministry_orders', 'Кыргыз Республикасынын Илим, жогорку билим берүү министрлигинин буйруктары'), ('nsu_orders', 'Нарын мамлекеттик университетинин буйруктары'), ('edu_plan', 'Окуу планы'), ('gos', 'ГОС'), ('smk1', 'CMK 1'), ('smk2', 'CMK 2'), ('smk3', 'CMK 3'), ('smk4', 'CMK 4'), ('smk5', 'CMK 5')], default='nsu_orders', max_length=50, verbose_name='Категория'),
        ),
    ]
